const computerScore=0;
const playerScore=0;
const playerScore_span=document.getElementById("player-score");
const computerScore_span=document.getElementById("computer-score");
const scoreBoard_div = document.querySelector(".scores");
const result_div = document.querySelector(".result");
const rock_div = document.getElementById("r");
const paper_div = document.getElementById("p");
const scissors_div = document.getElementById("s");
